# A minimal left prompt

# format = """$directory$character"""
command_timeout = 5000

# move the rest of the prompt to the right
# right_format = """$all"""

[aws]
symbol = "îŒ½  "
format = ' [$symbol($profile)(\($region\))( $duration)]($style)'

# [character]
# error_symbol = "[â¯](bold #ff5555)"
# success_symbol = "[â¯](bold #f8f8f2)"

[cmake]
format = ' [$symbol($version)]($style)'

[cmd_duration]
disabled = true
format = ' [ï¨š$duration]($style)'

[cobol]
format = ' [$symbol($version)]($style)'

[conda]
symbol = "ï„Œ "
format = ' [$symbol($version)]($style)'

[crystal]
format = ' [$symbol($version)]($style)'

[dart]
symbol = "î˜ "
format = ' [$symbol($version)]($style)'

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ï ½"

[deno]
format = ' [$symbol($version)]($style)'

[docker_context]
symbol = "ïŒˆ "
format = ' [$symbol$context]($style)'

[dotnet]
format = ' [$symbol($version)(ğŸ¯ $tfm)]($style)'

[elixir]
symbol = "î‰µ "
format = ' [$symbol($version \(OTP $otp_version\))]($style)'

[elm]
symbol = "î˜¬ "
format = ' [$symbol($version)]($style)'

[erlang]
format = ' [$symbol($version)]($style)'

[gcloud]
format = ' [$symbol$account(@$domain)(\($region\))]($style)'
disabled = true

[git_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = "î˜§ "
format = ' [$symbol($version)]($style)'

[helm]
format = ' [$symbol($version)]($style)'

[hg_branch]
symbol = "ï˜ "
format = ' [$symbol$branch]($style)'

[java]
symbol = "î‰– "
format = ' [$symbol($version)]($style)'

[julia]
symbol = "î˜¤ "
format = ' [$symbol($version)]($style)'

[kotlin]
format = ' [$symbol($version)]($style)'

[kubernetes]
format = ' [$symbol$context( \($namespace\))]($style)'

[lua]
symbol = "î˜  "
format = ' [$symbol($version)]($style)'

[memory_usage]
symbol = "ï¡š "
format = ' $symbol[$ram( | $swap)]($style)'

[nim]
symbol = "ïš¤ "
format = ' [$symbol($version)]($style)'

[nix_shell]
symbol = "ï‹œ "
format = ' [$symbol$state( \($name\))]($style)'

[nodejs]
symbol = "îœ˜ "
format = ' [$symbol($version)]($style)'

[ocaml]
format = ' [$symbol($version)(\($switch_indicator$switch_name\))]($style)'

[openstack]
format = ' [$symbol$cloud(\($project\))]($style)'

[package]
symbol = "ï£– "
format = ' [$symbol$version]($style)'

[perl]
symbol = "î© "
format = ' [$symbol($version)]($style)'

[php]
symbol = "î˜ˆ "
format = ' [$symbol($version)]($style)'

[pulumi]
format = ' [$symbol$stack]($style)'

[purescript]
format = ' [$symbol($version)]($style)'

[python]
symbol = "î˜† "
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[red]
format = ' [$symbol($version)]($style)'

[ruby]
symbol = "îˆ¾ "
format = ' [$symbol($version)]($style)'

[rust]
symbol = "î¨ "
format = ' [$symbol($version)]($style)'

[scala]
symbol = "îœ· "
format = ' [$symbol($version)]($style)'

[sudo]
format = ' [as $symbol]'

[shlvl]
symbol = "ï„  "

[swift]
symbol = "ï¯£ "
format = ' [$symbol($version)]($style)'

[terraform]
format = ' [$symbol$workspace]($style)'

[time]
format = '[$time]($style)'

[username]
format = ' [$user]($style)'

[vagrant]
format = ' [$symbol($version)]($style)'

[vlang]
format = ' [$symbol($version)]($style)'

[zig]
format = ' [$symbol($version)]($style)'
